"""Initial schema (§43).

Deliberate choice: this first revision builds the schema from the ORM metadata
rather than a hand-written list of ~20 `op.create_table` calls.

Why: a hand-transcribed initial migration can silently drift from the models,
and the only way to catch that is to run it against a real database. Deriving
it from `Base.metadata` makes drift impossible by construction.

This applies to the *initial* revision only. Every subsequent migration must be
a normal autogenerated one:

    docker compose exec api alembic revision --autogenerate -m "add x"

Autogenerate diffs against the models, so it works exactly as expected from
revision 0002 onward.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-18
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# Importing the package registers every table on Base.metadata.
import app.models  # noqa: F401
from app.models import Base

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
